### PR TITLE
Added optional sort options to all and query methods

### PR DESCRIPTION
**Pull request by twilson63**
This pull request is a proposal to add an optional sort parameter to the `all` and `query` methods.

Thanks

Tom

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@twilson63 Thnx for this PR, I was thinking of extending the query / all methods with additional params for a while now. You PR looks good for adding the sort order but looking at the https://support.mongolab.com/entries/20433053-rest-api-for-mongodb we can see that there are more useful parameters to be supported (skip, limit, include, exclude etc.). So if we assume that the second argument is for sorting we don't have much more space left for the future :-)

Maybe the second argument could be a hash with named arguments, something like:

``` javascript
{
    sort : {//sort criteria},
    limit : 10,
    //etc.
}
```

What do you think? Let me know if you would be interested in pushing your PR in this direction.

BTW: I like the fact that the backward-compatibility is not broken, there are tests and doc updates :-)

**Comment by twilson63** [comment]
Makes sense! And agree, I will be happy to refactor and re-submit.

Thanks

Tom

Sent from my iPhone

On Nov 18, 2012, at 11:58 AM, Pawel Kozlowski notifications@github.com
wrote:

@twilson63 https://github.com/twilson63 Thnx for this PR, I was thinking
of extending the query / all methods with additional params for a while
now. You PR looks good for adding the sort order but looking at the
https://support.mongolab.com/entries/20433053-rest-api-for-mongodb we can
see that there are more useful parameters to be supported (skip, limit,
include, exclude etc.). So if we assume that the second argument is for
sorting we don't have much more space left for the future :-)

Maybe the second argument could be a hash with named arguments, something
like:

{
    sort : {//sort criteria},
    limit : 10,
    //etc.}

What do you think? Let me know if you would be interested in pushing your
PR in this direction.

—
Reply to this email directly or view it on
GitHubhttps://github.com/pkozlowski-opensource/angularjs-mongolab-promise/pull/5#issuecomment-10488152.

**Comment by pkozlowski-opensource** [comment]
@twilson63 brilliant! Let me know if you need a hand with any of the code or tests. 

One minor thing: could you remove the configuration change for Testacular, the one that adds PhantomJS as a browser to be started automatically? Personally I'm using real browsers for testing and don't have PhantomJS installed. God catch for the `reporters` :-)

**Comment by twilson63** [comment]
Sure, I forgot about it.

Thx

Tom

Sent from my iPhone

On Nov 18, 2012, at 1:10 PM, Pawel Kozlowski notifications@github.com
wrote:

@twilson63 https://github.com/twilson63 brilliant! Let me know if you
need a hand with any of the code or tests.

One minor thing: could you remove the configuration change for Testacular,
the one that adds PhantomJS as a browser to be started automatically?
Personally I'm using real browsers for testing and don't have PhantomJS
installed. God catch for the reporters :-)

—
Reply to this email directly or view it on
GitHubhttps://github.com/pkozlowski-opensource/angularjs-mongolab-promise/pull/5#issuecomment-10489114.

**Comment by twilson63** [comment]
@pkozlowski-opensource 

Check out the latest commit when you have a moment and see if it is inline with your thoughts.

Thanks

Tom

**Comment by pkozlowski-opensource** [comment]
@twilson63Thnx, merged! Also added shortcut methods for `count` and `findOne`, thnx for inspiration :-)

**Comment by twilson63** [comment]
Awesome!

Thanks for the project and accepting the PR!

Thanks

Tom

On Tue, Nov 20, 2012 at 11:36 AM, Pawel Kozlowski
notifications@github.comwrote:

> @twilson63Thnx, merged! Also added shortcut methods for count and findOne,
> thnx for inspiration :-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pkozlowski-opensource/angularjs-mongolab-promise/pull/5#issuecomment-10561723.

## 

Tom Wilson
Jack Russell Software Company Division of CareKinesis
1067 Cliffwood Drive
Mount Pleasant, SC  29464
Phone: 843-606-0637
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar: http://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.

**Pull request merged**
